(defun template-replace (region-start-idx region-end-idx find-regex replace-regex)
  (interactive (let ((find-regexp (read-string "find: "))
		     (replace-regexp (read-string "replace: ")))
		 (list (region-beginning) (region-end) find-regexp replace-regexp)))
  (copy-region-as-kill region-start-idx region-end-idx)
  (setf (point) region-end-idx)
  (yank)
  (setf (point) region-end-idx)
  (let ((new-region-end-idx (+ (point) (- region-end-idx region-start-idx))))
    (replace-regexp find-regex replace-regex nil (point) new-region-end-idx)))
